=== Aphans/DAW/Lenguaje de marcas/3ºEVA/Tarea entregable/DTD/musica.dtd
<!ELEMENT musica (cd|musico)*>
<!ELEMENT cd EMPTY>
<!ATTLIST cd titulo CDATA #REQUIRED>
<!ATTLIST cd anho NMTOKEN #IMPLIED>
<!ATTLIST cd interprete NMTOKEN #REQUIRED>
<!ELEMENT musico (nombreArtistico,tipo?,instrumento*)>
<!ATTLIST musico codigo NMTOKEN #REQUIRED>
<!ELEMENT nombreArtistico (#PCDATA)>
<!ELEMENT tipo (#PCDATA)>
<!ELEMENT instrumento (#PCDATA)>

=== Aphans/DAW/Lenguaje de marcas/3ºEVA/Tarea entregable/DTD/tarea1_entregable.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE musica SYSTEM "musica.dtd">
<musica>
  <cd titulo="Late at nigth" anho="1999" interprete="SN2000"/>
  <cd titulo="Punto ... y seguido" anho="2006" interprete="CT9099"/>
  <cd titulo="Speak now" anho="2010" interprete="BV200"/>
  <musico codigo="SN2000">
    <nombreArtistico>Dover</nombreArtistico>
    <tipo>banda</tipo>
    <instrumento>bajo</instrumento>
    <instrumento>guitarra</instrumento>
    <instrumento>batería</instrumento>
  </musico>
  <musico codigo="CT9099">
    <nombreArtistico>Joaquín Sabina</nombreArtistico>
    <tipo>cantautor</tipo>
  </musico>
  <musico codigo="BV200">
    <nombreArtistico>Taylor Swift</nombreArtistico>
    <instrumento>guitarra</instrumento>
  </musico>
  <musico codigo="TUS100">
    <nombreArtistico>Carlos Nuñez</nombreArtistico>
    <instrumento>flauta de pico</instrumento>
    <instrumento>gaita</instrumento>
    <instrumento>ocarina</instrumento>
  </musico>
  <cd titulo="La hermandad de las estrellas" interprete="TUS100"/>
</musica>
