=== Aphans/DAW/Lenguaje de marcas/3ºEVA/DTD/Ejercicios DTD-20220307/bookmark.dtd
<!ELEMENT bookmark (origen,titulo,descripcion,grupo)>
<!ELEMENT origen (#PCDATA)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT grupo (archivo*,Contenido)>
<!ELEMENT archivo (#PCDATA)>
<!ELEMENT Contenido (#PCDATA)>
    <!ATTLIST grupo id CDATA #REQUIRED>
    <!ENTITY wap "wapdev_meta.xml">
    <!ENTITY wapfacil  "wapdev/wapfacil.xml">
    <!ENTITY asph  "wapdev/asphtml.xml">
    <!ENTITY cestaCompra "wapdev/cestacompra.xml">

=== Aphans/DAW/Lenguaje de marcas/3ºEVA/DTD/Ejercicios DTD-20220307/tarea9.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE bookmark SYSTEM "bookmark.dtd" [
 <!ENTITY wapfacil  "wapdev/wapfacil.xml">
 <!ENTITY wmlclub  "wapdev_meta.xml">
 <!ENTITY asphtml  "wapdev/asphtml.xml">
 <!ENTITY cestacompra  "wapdev/cestacompra.xml">
  <!ENTITY meta SYSTEM "meta.xml">
]>

<bookmark>
 <origen> “&meta;”</origen>
 <titulo>Información general sobre WAP</titulo>
 <descripcion>Recopilación de direcciones sobre WAP y WML.</descripcion>
 <grupo id="doc-portales">
    <archivo> "&wapfacil;" </archivo>
    <archivo> "&asphtml;" </archivo>
    <archivo> "&cestacompra;"</archivo>    
  </grupo>
</bookmark>
