=== Aphans/DAW/Lenguaje de marcas/3ºEVA/DTD/Ejercicios DTD-20220307/tarea11.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE compras[
<!ELEMENT compras (dvds,cintas)>
<!ELEMENT dvds (dvd+)>
<!ELEMENT dvd (titulo,pais,fecha_salida_mercado,actor?)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT pais (#PCDATA)>
<!ENTITY lista_fecha "día,año,mes">
<!ELEMENT fecha_salida_mercado (%lista_fecha;)>
<!ELEMENT día (#PCDATA)>
<!ELEMENT  mes (L | F | M | A | MAY | JUN |JUL | AG | S | O | N | D)>
<!ELEMENT año (#PCDATA)>
<!ELEMENT actor (#PCDATA)>
<!ATTLIST actor rol (protagonista |secundario) NMTOKEN #REQUIRED>
<!ELEMENT cintas (cinta)>
<!ELEMENT cinta (titulo,formato,portada,fecha_salida_mercado)>
<!ELEMENT formato (#PCDATA)>
<!ELEMENT portada (#PCDATA)>
<!NOTATION E SYSTEM "Enero">
<!NOTATION F SYSTEM "Febrero">
<!NOTATION M SYSTEM "Marzo">
<!NOTATION A SYSTEM "Abril">
<!NOTATION MAY SYSTEM "Mayo">
<!NOTATION JUN SYSTEM "Junio">
<!NOTATION JUL SYSTEM "Julio">
<!NOTATION AG SYSTEM "Agosto">
<!NOTATION S SYSTEM "Septiembre">
<!NOTATION O SYSTEM "Octubre">
<!NOTATION N SYSTEM "Noviembre">
<!NOTATION D SYSTEM "Diciembre">
<!ENTITY titulo ="El oro de Moscú">
<!ENTITY titulo2 = "Terminator">
<!ENTITY titulo3 ="Gladiator">
<!ENTITY % fecha_salida_mercado ("dia #PCDATA mes #PCDATA año #PCDTA")>
]>

=== Aphans/DAW/Lenguaje de marcas/3ºEVA/DTD/Ejercicios DTD-20220307/Tarea11.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE compras SYSTEM "tarea11.dtd">
<compras>
     <dvds>
    <dvd>
        <titulo>&titulo;</titulo>
        <pais>España</pais>
        <fecha_salida_mercado>
        <día> 01 </día>
        <mes> E</mes>
        <año> 2006</año>
        </fecha_salida_mercado>
    </dvd>
    <dvd>
        <titulo>&titulo2;</titulo>
        <pais>EEUU</pais>
        <actor rol = "protagonista"> Arnold S.</actor>
        <fecha_salida_mercado>
        <día> 01 </día>
        <mes> M</mes>
        <año> 1992</año>
        </fecha_salida_mercado>
    </dvd>
 </dvds>
 <cintas>
    <cinta>
       <titulo>&titulo3;</titulo>
       <formato>VHS</formato>
       <portada>https://portada_gladiator/fotaca.img</portada>
       <fecha_salida_mercado>
        <día> 01 </día>
        <mes> NV</mes>
        <año> 2000</año>
        </fecha_salida_mercado>
    </cinta>
 </cintas>
 </compras>
