=== Aphans/DAW/Lenguaje de marcas/3ºEVA/DTD/Ejercicios DTD-20220307/tarea6.dtd
<!ELEMENT edificio (direccion, fechaConstruccion, material?)>
    <!ELEMENT direccion (calle, numero, poblacion, provincia, codigoPostal)>
    <!ELEMENT calle (#PCDATA)>
    <!ELEMENT numero (#PCDATA)>
    <!ELEMENT poblacion (#PCDATA)>
    <!ELEMENT provincia (#PCDATA)>
    <!ELEMENT codigoPostal (#PCDATA)>
    <!ELEMENT fechaConstruccion EMPTY>
    <!ATTLIST fechaConstruccion
          mes CDATA #REQUIRED
          anho CDATA #REQUIRED>
    <!ELEMENT material (#PCDATA)>
    <!ATTLIST edificio
          valor CDATA #IMPLIED
          alquiler (verdadero|falso) #REQUIRED>

=== Aphans/DAW/Lenguaje de marcas/3ºEVA/DTD/Ejercicios DTD-20220307/tarea6.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE edificio SYSTEM "tarea6.dtd">
<edificio alquiler="verdadero">
<direccion>
    <calle>
        C/No sÃ©
    </calle>   
    <numero>
        3
    </numero>
    <poblacion>
        Madrid
    </poblacion>
    <provincia>
        Madrid
    </provincia>
    <codigoPostal>
        2900
    </codigoPostal>
</direccion>
    <fechaConstruccion mes="44040" anho="333"/>
    <material>
    </material>
</edificio>
